# This is a basic workflow to help you get started with Actions

name: Lint

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  pull_request:
    branches: [ main ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: self-hosted

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v3
        with:
          python-version: "3.8"
          cache: 'pip'
      - run: python -m ensurepip --upgrade
      - run: pip install -r requirements.txt

      # Runs a set of commands using the runners shell
      - name: Lint config
        id: lc
        continue-on-error: true
        env:
          SPLUNK_PASS: ${{ secrets.SPLUNK_PASS }}
        run: |
          python lint.py
          body=$(cat output.txt)
          body="${body//'%'/'%25'}"
          body="${body//$'\n'/'%0A'}"
          body="${body//$'\r'/'%0D'}"
          echo "::set-output name=body::$body"
      - name: Write comment
        uses: peter-evans/create-or-update-comment@v2
        with:
          issue-number: ${{ github.event.pull_request.number }}
          body: |
            ## Lint results
            ${{ steps.lc.outputs.body }}
      - name: check for lint failure
        if: steps.lc.outputs.status == 'failure'
        run: |
          exit 1

          
          
